name: Project Tests

on:
  push:
    branches:
    - main
    paths:
      - project/**

jobs:
  project-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    # Install sqlalchemy
    - name: Install sqlalchemy
      run: python -m pip install --upgrade pip sqlalchemy

    # Install pandas
    - name: Install pandas
      run: python -m pip install --upgrade pip pandas    
    
    # Run project tests
    - name: Project tests
      run: |
        cd ./main/project
        chmod +x tests.sh
        ./tests.sh